# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e
      MYSQL_DATABASE: atb
    ports:
      - 3306:3306

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
  web:
    image: webapp
    volumes:
     - /app:/app
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    links:
      - db
#    command: bash -c "echo gagagaga;pip install -q -r /app/req.txt"
# #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/atbsite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

