FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
RUN apk --update add bash nano
RUN pip install  -q mysql-connector-python mysql-connector-python
# RUN ln -s /app/webapp.nginx.conf /etc/nginx/conf.d/webapp.conf

